#185218915 Users should be able to Login via Google.
atlp-rwanda/e-comm-team-techsmith-fn pull request #19
Opened 2023-05-30 02:07 UTC by irakevine

## What does this PR do?
This PR allows Users sign into a Google account, which helps you to quickly and easily manage user authentication on your website.
## Description of Task to be completed?
-  Provide their consent, and securely share their profile information with your platform. 
-  Customizable buttons and multiple flows are supported for user sign-up and sign-in.
-  Adding Pull Request template adhering to ATLP's Engineering Playbook

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn.git` 

- Checkout to the branch using `git checkout ft-users-should-be-able-to-login-via-google-185218915`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

## What are the relevant pivotal tracker/Trello stories?
+[185218915](https://www.pivotaltracker.com/story/show/185218915)

2023-06-11 23:48 UTC, nishimweprince approved these changes
Excellent work @irakevine !!

2023-06-11 23:51 UTC, jcharles921 approved these changes
Great work , well done 👍🏽

2023-06-11 23:55 UTC, frankflej approved these changes
Excellent!

2023-06-11 23:57 UTC, ReneNtabana approved these changes
nicely done! Kevine.

2023-06-12 00:13 UTC, niyontwali requested changes

2023-06-12 00:13 UTC, niyontwali commented on src/containers/LoginContainer.jsx
> +           <Link to='https://e-comm-team-techsmith-bn-staging-fmp3.onrender.com/api/auth/google'>
Include this in the .env, I mean the base url since we believe this might change in the future

2023-06-12 00:13 UTC, niyontwali commented on src/states/allReducers.js
> +export default allReducers;
This file should not appear here

2023-06-12 00:13 UTC, niyontwali commented
Please rebase carefully, I can still see folders and files that are nolonger being used.

2023-06-12 00:35 UTC, nishimweprince approved these changes
Excellent work!

2023-06-12 00:39 UTC, niyontwali approved these changes

2023-06-12 00:39 UTC, ReneNtabana approved these changes

2023-06-12 00:44 UTC, merged