#185218918: Two factor authentication for the seller
atlp-rwanda/e-comm-team-techsmith-fn pull request #26
Opened 2023-06-05 01:34 UTC by Gabriel-mdv

## What does this PR do?
- Ensures Two Factor authentication for the seller
- Adds a `remember me` button on the login page

## Description of Task to be completed?
- GIVEN there is a request to log in a user to the website
- WHEN 2FA is enabled on the particular user
- THEN Further request for a 2FA token should be requested and once the token is received and validated, the user is allowed to log in.

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

- Check out the components documentation: `npm run storybook`

## What are the relevant pivotal tracker/Trello stories?
- [185218918](https://www.pivotaltracker.com/story/show/185218918)

## Screenshots (if appropriate)
![Two factor authentication]()
![Remember me]()

2023-06-05 11:19 UTC, jcharles921 approved these changes
great

2023-06-05 18:37 UTC, Dyves1 approved these changes

2023-06-05 19:16 UTC, frankflej commented on src/components/InputPopup.jsx
I think you should make some changes its not necessary to reuse again useStates on inputs to capture differents events occuring on the input because register from form hooks does that

2023-06-05 19:24 UTC, nishimweprince requested changes
I added comments for your review.

2023-06-05 19:24 UTC, nishimweprince commented on src/components/backup.md
Why do we have this file?

2023-06-05 19:24 UTC, nishimweprince commented on src/containers/LoginContainer.jsx
> +localStorage.setItem('rememberedPassword', data.password);
I would not suggest to store a user's password in localStorage without *hashing* it as it makes it vulnerable. Please hashing it using byrcyptjs (bycrypt for the frontend), you may refer to its documentation here: [bcrypt.js - npm](https://www.npmjs.com/package/bcryptjs), then decrypt it again on line 69 when you fetch it back from localStorage.

2023-06-05 19:24 UTC, nishimweprince commented on src/styles/index.scss
> +  font-family: 'Poppins', sans-serif !important;
You can change the font here as the team agreed to shift to Inter.

2023-06-06 09:48 UTC, irakevine approved these changes
Great Work

2023-06-06 09:50 UTC, frankflej approved these changes
its now perfect

2023-06-06 09:58 UTC, nishimweprince approved these changes
Excellent work!!

2023-06-06 10:00 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 10:01 UTC, irakevine approved these changes
Great Work

2023-06-06 11:21 UTC, niyontwali approved these changes

2023-06-06 11:21 UTC, merged