#185218925 Admin should be able to view all accounts  as well as set roles/permissions
atlp-rwanda/e-comm-team-techsmith-fn pull request #32
Opened 2023-06-08 07:29 UTC by cyubahiro367

## What does this PR do?

This PR create a dashboard for the administrators to be able to manage accounts 

## Description of Task to be completed?

Admin dashboard should list all users with the option of grant permission the the user account like as seller, buyer or admin

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn`

- Checkout to the branch using `git checkout <branch-name>`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

- Check out the components documentation: `npm run storybook`

## Any background context you want to provide?

## What are the relevant pivotal tracker/Trello stories?

- [#185218925](https://www.pivotaltracker.com/story/show/185218925)

## Screenshots (if appropriate)

## Questions:

2023-06-15 08:58 UTC, Dyves1 reviewed
I think you can use toast instead of snackbar

2023-06-15 17:01 UTC, jcharles921 requested changes
You have 2 commits , you should stash

2023-06-16 19:19 UTC, jcharles921 reviewed
another minor change for the commit message you should change it to 
`[delivers #185218925] ` for pivol tracker to link well your branch.

2023-06-17 19:03 UTC, bergad37 reviewed
Why are you using Snackbar at the same time with Toastify?

2023-06-18 09:07 UTC, jcharles921 approved these changes

2023-06-18 20:34 UTC, Gabriel-mdv requested changes
very good job on this. However:
1. The `userList` from the containers folder was imported into `usersContainer`. It makes more sense to put userList in the components folder instead of importing it as a container into another container.  
2. changing the role of one user is showing loading effects on all role fields for all users on the page. Is there any way you can only show loading for the changed user.?

2023-06-19 11:11 UTC, mken1205 approved these changes

2023-06-19 23:28 UTC, jcharles921 commented
> very good job on this. However:
> 
>     1. The `userList` from the containers folder was imported into `usersContainer`. It makes more sense to put userList in the components folder instead of importing it as a container into another container.
> 
>     2. changing the role of one user is showing loading effects on all role fields for all users on the page. Is there any way you can only show loading for the changed user.?

i think it is ok to put the` userlist` as a container because it is not reused anywhere else in the code base and we also di the same thing for the landing page where we have more than one container are imported to the home container ...

2023-06-19 23:31 UTC, nishimweprince approved these changes
Great work @cyubahiro367 !!

2023-06-19 23:32 UTC, irakevine approved these changes
Great Work

2023-06-19 23:32 UTC, irakevine commented on src/containers/Userlist.jsx
I was wondering about this MUI
you removed it so we can all have the same codebase as team

2023-06-19 23:35 UTC, Gabriel-mdv approved these changes
pretty nice work!

2023-06-20 07:21 UTC, bergad37 approved these changes
Nice work!

2023-06-20 08:00 UTC, merged