#185218904 implement Setup redux
atlp-rwanda/e-comm-team-techsmith-fn pull request #4
Opened 2023-05-20 16:09 UTC by irakevine

## What does this PR do?

This PR sets up Redux it help us to manage our app's state in a single place and keep changes in our app more predictable and traceable.

## Description of Task to be completed?

- it allows React components to read data from a Redux Store
- dispatch Actions to the Store to update data. 
- Redux helps apps to scale by providing a sensible way to manage state through a unidirectional data flow model.

## How should this be manually tested?

- Clone the repository using `git clone https://github.com/atlp-rwanda/e-comm-team-techsmith-fn.git` 

- Checkout to the branch using `git checkout ch-redux-setup-185218904`

- Install node packages that the application depends on: `npm i`

- Create a `.env` file in the root directory and add all environment variables required to run the application. The required variables are listed in the `.env.example` file available in root directory of the application.

- Start the application development server: `npm start`

## What are the relevant pivotal tracker/Trello stories?

+ [#185218904](https://www.pivotaltracker.com/story/show/185218904)

2023-05-20 21:36 UTC, nishimweprince requested changes
I suggested changes in comments

2023-05-20 21:36 UTC, nishimweprince commented on package.json
> +    "start": "react-scripts start",
You will have to omit react-scripts in a vite project. Please refer to this [link](https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite) in section 8 for your reference.

2023-05-21 16:53 UTC, jcharles921 approved these changes

2023-05-21 20:21 UTC, irakozejules approved these changes

2023-05-21 21:13 UTC, nishimweprince approved these changes

2023-05-22 08:04 UTC, Dyves1 approved these changes
Great

2023-05-22 08:10 UTC, ReneNtabana approved these changes

2023-05-22 08:13 UTC, frankflej approved these changes
Nice work!

2023-05-22 08:21 UTC, Tparfaite approved these changes

2023-05-22 08:25 UTC, bergad37 approved these changes

2023-05-22 08:26 UTC, bergad37 approved these changes
Cool!well done.

2023-05-22 11:41 UTC, merged